name: code-climate
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - uses: qltysh/qlty-action/coverage@v1
        with:
          token: secrets.QLTY_COVERAGE_TOKEN
          files: target/lcov.info
