name: mysels-actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - name: run lint
        run: npx eslint .
      - name: run tests
        run: npm test
      - uses: qltysh/qlty-action/coverage@v1
  with:
    token: { { secrets.QLTY_COVERAGE_TOKEN } }
    files: coverage/lcov.info
